
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 4;
  public static final int Suma = 7;
  public static final int Numero = 18;
  public static final int Identificador = 17;
  public static final int Int = 2;
  public static final int Llave_c = 14;
  public static final int Llave_a = 13;
  public static final int P_coma = 16;
  public static final int Main = 15;
  public static final int EOF = 0;
  public static final int Division = 10;
  public static final int Resta = 8;
  public static final int If = 3;
  public static final int error = 1;
  public static final int Igual = 6;
  public static final int While = 5;
  public static final int Multiplicacion = 9;
  public static final int Parenthesis_c = 12;
  public static final int Error = 19;
  public static final int Parenthesis_a = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Int",
  "If",
  "Else",
  "While",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Parenthesis_a",
  "Parenthesis_c",
  "Llave_a",
  "Llave_c",
  "Main",
  "P_coma",
  "Identificador",
  "Numero",
  "Error"
  };
}

